"""Add needs_onboarding to user

Revision ID: 00d3ac121e5e
Revises: e4b97045c365
Create Date: 2026-03-21 09:38:13.500017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00d3ac121e5e'
down_revision: Union[str, None] = 'e4b97045c365'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
