"""add supplier and enhance purchase

Revision ID: 1469d663ec25
Revises: 3db596d99100
Create Date: 2025-12-29 11:15:21.283665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1469d663ec25'
down_revision: Union[str, None] = '3db596d99100'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True, comment='Short code like SUP001'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('supplier', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supplier_name'), ['name'], unique=False)

    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reference', sa.String(length=64), nullable=True, comment='Unique PO reference like PO-0001'))
        batch_op.add_column(sa.Column('supplier_id', sa.Integer(), nullable=True, comment='Link to Supplier entity (preferred)'))
        batch_op.add_column(sa.Column('supplier_reference', sa.String(length=100), nullable=True, comment="Supplier's order reference code"))
        batch_op.add_column(sa.Column('target_date', sa.Date(), nullable=True, comment='Expected delivery date'))
        batch_op.add_column(sa.Column('destination', sa.String(length=255), nullable=True, comment='Default location for received items'))
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('received_by_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_purchase_reference'), ['reference'], unique=True)
        batch_op.create_index(batch_op.f('ix_purchase_supplier_id'), ['supplier_id'], unique=False)
        batch_op.create_foreign_key('fk_purchase_supplier', 'supplier', ['supplier_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_purchase_received_by', 'user', ['received_by_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_purchase_created_by', 'user', ['created_by_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('purchase_line', schema=None) as batch_op:
        batch_op.add_column(sa.Column('destination', sa.String(length=255), nullable=True, comment='Override location for this line'))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_line', schema=None) as batch_op:
        batch_op.drop_column('notes')
        batch_op.drop_column('destination')

    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_purchase_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_reference'))
        batch_op.drop_column('received_by_id')
        batch_op.drop_column('created_by_id')
        batch_op.drop_column('destination')
        batch_op.drop_column('target_date')
        batch_op.drop_column('supplier_reference')
        batch_op.drop_column('supplier_id')
        batch_op.drop_column('reference')

    with op.batch_alter_table('supplier', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplier_name'))

    op.drop_table('supplier')
    # ### end Alembic commands ###
