"""add_user_presence_and_participants

Revision ID: 193b04446e99
Revises: 1469d663ec25
Create Date: 2025-12-29 17:13:46.110134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '193b04446e99'
down_revision: Union[str, None] = '1469d663ec25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('procedure_instance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('participants', sa.JSON(), nullable=True, comment='Active users: [{user_id, joined_at, last_step}]'))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True, comment='Heartbeat timestamp for presence'))
        batch_op.add_column(sa.Column('current_activity', sa.String(length=255), nullable=True, comment='Current activity: executing:123, viewing:parts:45'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('current_activity')
        batch_op.drop_column('last_seen_at')

    with op.batch_alter_table('procedure_instance', schema=None) as batch_op:
        batch_op.drop_column('participants')

    # ### end Alembic commands ###
