"""add manufacturing enhancements

Revision ID: 3db596d99100
Revises: ed7deb9d898c
Create Date: 2025-12-29 04:25:55.142500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3db596d99100'
down_revision: Union[str, None] = 'ed7deb9d898c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workcenter',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False, comment='Short code like AB1, CR'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True, comment='Physical location'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('workcenter', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workcenter_name'), ['name'], unique=False)

    op.create_table('step_kit',
    sa.Column('step_id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('quantity_required', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('usage_type', sa.String(length=20), nullable=False, comment='consume = inventory decremented, tooling = reused'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['part_id'], ['part.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['step_id'], ['procedure_step.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('step_kit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_step_kit_part_id'), ['part_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_step_kit_step_id'), ['step_id'], unique=False)

    with op.batch_alter_table('inventory_consumption', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usage_type', sa.String(length=20), nullable=False, server_default='consume', comment='consume = permanent, tooling = returned'))
        batch_op.add_column(sa.Column('step_execution_id', sa.Integer(), nullable=True, comment='Which step consumed this part'))
        batch_op.create_index(batch_op.f('ix_inventory_consumption_step_execution_id'), ['step_execution_id'], unique=False)
        batch_op.create_foreign_key('fk_inv_consumption_step_exec', 'step_execution', ['step_execution_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('master_procedure', schema=None) as batch_op:
        batch_op.add_column(sa.Column('procedure_type', sa.String(length=20), nullable=False, server_default='op', comment='op = work order, build = produces assembly'))

    with op.batch_alter_table('procedure_step', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_step_id', sa.Integer(), nullable=True, comment='NULL = top-level OP, set = sub-step'))
        batch_op.add_column(sa.Column('step_number', sa.String(length=20), nullable=False, server_default='1', comment='Display number: 1, 1.1, 1.2, 2'))
        batch_op.add_column(sa.Column('level', sa.Integer(), nullable=False, server_default='0', comment='0 = major OP, 1 = sub-step'))
        batch_op.add_column(sa.Column('workcenter_id', sa.Integer(), nullable=True, comment='Default workcenter for this step'))
        batch_op.create_index(batch_op.f('ix_procedure_step_parent_step_id'), ['parent_step_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_procedure_step_workcenter_id'), ['workcenter_id'], unique=False)
        batch_op.create_foreign_key('fk_step_workcenter', 'workcenter', ['workcenter_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_step_parent', 'procedure_step', ['parent_step_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('step_execution', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workcenter_id', sa.Integer(), nullable=True, comment='Actual workcenter where step was performed'))
        batch_op.create_index(batch_op.f('ix_step_execution_workcenter_id'), ['workcenter_id'], unique=False)
        batch_op.create_foreign_key('fk_stepexec_workcenter', 'workcenter', ['workcenter_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('step_execution', schema=None) as batch_op:
        batch_op.drop_constraint('fk_stepexec_workcenter', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_step_execution_workcenter_id'))
        batch_op.drop_column('workcenter_id')

    with op.batch_alter_table('procedure_step', schema=None) as batch_op:
        batch_op.drop_constraint('fk_step_workcenter', type_='foreignkey')
        batch_op.drop_constraint('fk_step_parent', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_procedure_step_workcenter_id'))
        batch_op.drop_index(batch_op.f('ix_procedure_step_parent_step_id'))
        batch_op.drop_column('workcenter_id')
        batch_op.drop_column('level')
        batch_op.drop_column('step_number')
        batch_op.drop_column('parent_step_id')

    with op.batch_alter_table('master_procedure', schema=None) as batch_op:
        batch_op.drop_column('procedure_type')

    with op.batch_alter_table('inventory_consumption', schema=None) as batch_op:
        batch_op.drop_constraint('fk_inv_consumption_step_exec', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_inventory_consumption_step_execution_id'))
        batch_op.drop_column('step_execution_id')
        batch_op.drop_column('usage_type')

    with op.batch_alter_table('step_kit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_step_kit_step_id'))
        batch_op.drop_index(batch_op.f('ix_step_kit_part_id'))

    op.drop_table('step_kit')
    with op.batch_alter_table('workcenter', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workcenter_name'))

    op.drop_table('workcenter')
    # ### end Alembic commands ###
