"""add_expiration_date_to_inventory

Revision ID: 6ef042183637
Revises: 6fd5ab3b7c0b
Create Date: 2026-02-17 00:45:30.469750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ef042183637'
down_revision: Union[str, None] = '6fd5ab3b7c0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expiration_date', sa.Date(), nullable=True, comment='Expiration date for perishable materials'))
        batch_op.create_index(batch_op.f('ix_inventory_record_expiration_date'), ['expiration_date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_record_expiration_date'))
        batch_op.drop_column('expiration_date')

    # ### end Alembic commands ###
