"""add_reorder_point_to_part

Revision ID: 6fd5ab3b7c0b
Revises: 8c28773a540e
Create Date: 2026-02-17 00:06:33.722479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fd5ab3b7c0b'
down_revision: Union[str, None] = '8c28773a540e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issue', schema=None) as batch_op:
        batch_op.alter_column('issue_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    with op.batch_alter_table('part', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reorder_point', sa.Numeric(precision=15, scale=4), nullable=True, comment='Quantity threshold below which part is considered low stock'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('part', schema=None) as batch_op:
        batch_op.drop_column('reorder_point')

    with op.batch_alter_table('issue', schema=None) as batch_op:
        batch_op.alter_column('issue_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###
