"""add needs_profile_setup to user

Revision ID: 74ae45c61c41
Revises: 90c2c727cf6c
Create Date: 2026-02-19 13:08:01.735040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74ae45c61c41'
down_revision: Union[str, None] = '90c2c727cf6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('needs_profile_setup', sa.Boolean(), nullable=False, server_default=sa.text('0')))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('needs_profile_setup')

    # ### end Alembic commands ###
