"""add exe_user_id to user

Revision ID: 90c2c727cf6c
Revises: ec12ee94b679
Create Date: 2026-02-18 23:07:51.955761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90c2c727cf6c'
down_revision: Union[str, None] = 'ec12ee94b679'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exe_user_id', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint('uq_user_exe_user_id', ['exe_user_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_exe_user_id', type_='unique')
        batch_op.drop_column('exe_user_id')

    # ### end Alembic commands ###
