"""add inventory consumption table

Revision ID: 90e94a084627
Revises: e6f4afdc06e9
Create Date: 2025-12-29 03:49:04.333721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90e94a084627'
down_revision: Union[str, None] = 'e6f4afdc06e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_consumption',
    sa.Column('inventory_record_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=15, scale=4), nullable=False, comment='Positive value = consumed'),
    sa.Column('consumption_type', sa.String(length=20), nullable=False),
    sa.Column('procedure_instance_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('consumed_by_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['consumed_by_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['inventory_record_id'], ['inventory_record.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['procedure_instance_id'], ['procedure_instance.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_consumption', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_consumption_inventory_record_id'), ['inventory_record_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_consumption_procedure_instance_id'), ['procedure_instance_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_consumption', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_consumption_procedure_instance_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_consumption_inventory_record_id'))

    op.drop_table('inventory_consumption')
    # ### end Alembic commands ###
