"""add_build_scheduling_fields

Revision ID: 93b2946223cb
Revises: b9c477a67e75
Create Date: 2025-12-29 17:33:36.623861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93b2946223cb'
down_revision: Union[str, None] = 'b9c477a67e75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('procedure_instance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scheduled_start_at', sa.DateTime(timezone=True), nullable=True, comment='When work is planned to start'))
        batch_op.add_column(sa.Column('target_completion_at', sa.DateTime(timezone=True), nullable=True, comment='Due date for completion'))
        batch_op.add_column(sa.Column('priority', sa.Integer(), nullable=False, server_default='0', comment='Higher = more urgent (0=normal, 1=high, 2=urgent)'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('procedure_instance', schema=None) as batch_op:
        batch_op.drop_column('priority')
        batch_op.drop_column('target_completion_at')
        batch_op.drop_column('scheduled_start_at')

    # ### end Alembic commands ###
