"""add internal_pn to part

Revision ID: 9d685df5636f
Revises: 78a35eabd240
Create Date: 2026-01-12 19:26:20.381252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d685df5636f'
down_revision: Union[str, None] = '78a35eabd240'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_record', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_inventory_record_opal_number'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_inventory_record_opal_number'))
        batch_op.create_index(batch_op.f('ix_inventory_record_opal_number'), ['opal_number'], unique=True)

    with op.batch_alter_table('issue', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_issue_issue_number'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_issue_issue_number'))
        batch_op.create_index(batch_op.f('ix_issue_issue_number'), ['issue_number'], unique=True)

    with op.batch_alter_table('part', schema=None) as batch_op:
        batch_op.add_column(sa.Column('internal_pn', sa.String(length=50), nullable=True, comment='Internal part number from project config (e.g., PO/1-001)'))
        batch_op.create_index(batch_op.f('ix_part_internal_pn'), ['internal_pn'], unique=True)

    with op.batch_alter_table('risk', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_risk_risk_number'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_risk_risk_number'))
        batch_op.create_index(batch_op.f('ix_risk_risk_number'), ['risk_number'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('risk', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_risk_number'))
        batch_op.create_index(batch_op.f('ix_risk_risk_number'), ['risk_number'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('uq_risk_risk_number'), ['risk_number'])

    with op.batch_alter_table('part', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_part_internal_pn'))
        batch_op.drop_column('internal_pn')

    with op.batch_alter_table('issue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_issue_issue_number'))
        batch_op.create_index(batch_op.f('ix_issue_issue_number'), ['issue_number'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('uq_issue_issue_number'), ['issue_number'])

    with op.batch_alter_table('inventory_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_record_opal_number'))
        batch_op.create_index(batch_op.f('ix_inventory_record_opal_number'), ['opal_number'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('uq_inventory_record_opal_number'), ['opal_number'])

    # ### end Alembic commands ###
