"""add_stock_transfers

Revision ID: b9c477a67e75
Revises: f8088eeb1add
Create Date: 2025-12-29 17:29:51.536626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9c477a67e75'
down_revision: Union[str, None] = 'f8088eeb1add'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_transfer',
    sa.Column('source_inventory_id', sa.Integer(), nullable=True, comment='Source inventory record (may be null if source deleted)'),
    sa.Column('target_inventory_id', sa.Integer(), nullable=True, comment='Target inventory record (created on transfer)'),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=15, scale=4), nullable=False, comment='Quantity transferred'),
    sa.Column('source_location', sa.String(length=255), nullable=False, comment='Original location'),
    sa.Column('target_location', sa.String(length=255), nullable=False, comment='Destination location'),
    sa.Column('source_lot_number', sa.String(length=100), nullable=True),
    sa.Column('target_lot_number', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('transferred_by_id', sa.Integer(), nullable=True),
    sa.Column('transferred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['part_id'], ['part.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_inventory_id'], ['inventory_record.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_inventory_id'], ['inventory_record.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transferred_by_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_transfer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_transfer_part_id'), ['part_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_transfer_source_inventory_id'), ['source_inventory_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_transfer_target_inventory_id'), ['target_inventory_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_transfer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_transfer_target_inventory_id'))
        batch_op.drop_index(batch_op.f('ix_stock_transfer_source_inventory_id'))
        batch_op.drop_index(batch_op.f('ix_stock_transfer_part_id'))

    op.drop_table('stock_transfer')
    # ### end Alembic commands ###
