"""Add requires_signoff and step notes

Revision ID: d85e2bcfadb7
Revises: a1b2c3d4e5f6
Create Date: 2026-02-22 01:03:44.848732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd85e2bcfadb7'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('procedure_step', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requires_signoff', sa.Boolean(), nullable=False, server_default=sa.text('0'), comment='Step requires sign-off to complete'))

    with op.batch_alter_table('step_execution', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True, comment='Free-text operator notes'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('step_execution', schema=None) as batch_op:
        batch_op.drop_column('notes')

    with op.batch_alter_table('procedure_step', schema=None) as batch_op:
        batch_op.drop_column('requires_signoff')

    # ### end Alembic commands ###
