"""Add Onshape integration tables

Revision ID: de85a4fdcd2a
Revises: d85e2bcfadb7
Create Date: 2026-02-24 00:14:26.645424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de85a4fdcd2a'
down_revision: Union[str, None] = 'd85e2bcfadb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('onshape_link',
    sa.Column('part_id', sa.Integer(), nullable=False, comment='OPAL Part this link references'),
    sa.Column('document_id', sa.String(length=50), nullable=False, comment='Onshape document ID'),
    sa.Column('element_id', sa.String(length=50), nullable=False, comment='Onshape element (part studio / assembly) ID'),
    sa.Column('part_id_onshape', sa.String(length=50), nullable=False, comment='Part ID within the Onshape element'),
    sa.Column('onshape_name', sa.String(length=255), nullable=True, comment='Part name as it appears in Onshape'),
    sa.Column('onshape_part_number', sa.String(length=255), nullable=True, comment='Part number as set in Onshape'),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of last successful sync'),
    sa.Column('pull_hash', sa.String(length=64), nullable=True, comment='SHA-256 of Onshape data at last pull (for change detection)'),
    sa.Column('push_hash', sa.String(length=64), nullable=True, comment='SHA-256 of OPAL ERP data at last push (for change detection)'),
    sa.Column('stale', sa.Boolean(), nullable=False, comment='True if Onshape part was not found during last sync'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['part_id'], ['part.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('onshape_link', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_onshape_link_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_onshape_link_part_id'), ['part_id'], unique=True)

    op.create_table('onshape_sync_log',
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False, comment='When the sync operation started'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='When the sync operation completed (null if still running or failed)'),
    sa.Column('direction', sa.String(length=10), nullable=False, comment="Sync direction: 'pull' or 'push'"),
    sa.Column('trigger', sa.String(length=20), nullable=False, comment="What triggered the sync: 'manual', 'poll', or 'webhook'"),
    sa.Column('status', sa.String(length=20), nullable=False, comment="Sync status: 'running', 'success', 'partial', 'error'"),
    sa.Column('document_id', sa.String(length=50), nullable=True, comment='Onshape document ID that was synced'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='User who triggered the sync (null for automated syncs)'),
    sa.Column('parts_created', sa.Integer(), nullable=False),
    sa.Column('parts_updated', sa.Integer(), nullable=False),
    sa.Column('bom_lines_created', sa.Integer(), nullable=False),
    sa.Column('bom_lines_updated', sa.Integer(), nullable=False),
    sa.Column('bom_lines_removed', sa.Integer(), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=True, comment='Error details if sync failed or partially succeeded'),
    sa.Column('summary', sa.Text(), nullable=True, comment='Human-readable sync summary'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('onshape_sync_log')
    with op.batch_alter_table('onshape_link', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_onshape_link_part_id'))
        batch_op.drop_index(batch_op.f('ix_onshape_link_document_id'))

    op.drop_table('onshape_link')
    # ### end Alembic commands ###
