"""Add type-specific issue fields

Revision ID: e4b97045c365
Revises: ecccad46c669
Create Date: 2026-03-21 07:52:57.234817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4b97045c365'
down_revision: Union[str, None] = 'ecccad46c669'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('should_be', sa.Text(), nullable=True, comment='NC: expected condition'))
        batch_op.add_column(sa.Column('is_condition', sa.Text(), nullable=True, comment='NC: actual condition'))
        batch_op.add_column(sa.Column('steps_to_reproduce', sa.Text(), nullable=True, comment='Bug: repro steps'))
        batch_op.add_column(sa.Column('expected_behavior', sa.Text(), nullable=True, comment='Bug: expected'))
        batch_op.add_column(sa.Column('actual_behavior', sa.Text(), nullable=True, comment='Bug: actual'))
        batch_op.add_column(sa.Column('expected_benefit', sa.Text(), nullable=True, comment='Improvement: benefit'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issue', schema=None) as batch_op:
        batch_op.drop_column('expected_benefit')
        batch_op.drop_column('actual_behavior')
        batch_op.drop_column('expected_behavior')
        batch_op.drop_column('steps_to_reproduce')
        batch_op.drop_column('is_condition')
        batch_op.drop_column('should_be')

    # ### end Alembic commands ###
