"""Initial migration

Revision ID: e6f4afdc06e9
Revises: 
Create Date: 2025-12-28 16:59:26.854806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6f4afdc06e9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_procedure',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_version_id', sa.Integer(), nullable=True, comment='Points to latest published version'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['current_version_id'], ['procedure_version.id'], ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('master_procedure', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_master_procedure_name'), ['name'], unique=False)

    op.create_table('part',
    sa.Column('external_pn', sa.String(length=255), nullable=True, comment='Manufacturer/supplier part number'),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('unit_of_measure', sa.String(length=20), nullable=False, comment='ea, kg, m, etc.'),
    sa.Column('metadata', sa.JSON(), nullable=True, comment='Flexible additional fields'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('part', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_part_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_part_external_pn'), ['external_pn'], unique=False)
        batch_op.create_index(batch_op.f('ix_part_name'), ['name'], unique=False)

    op.create_table('purchase',
    sa.Column('supplier', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('ordered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_supplier'), ['supplier'], unique=False)

    op.create_table('user',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('old_values', sa.JSON(), nullable=True, comment='Previous values (null for create)'),
    sa.Column('new_values', sa.JSON(), nullable=True, comment='New values (null for delete)'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_record_id'), ['record_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_table_name'), ['table_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_user_id'), ['user_id'], unique=False)

    op.create_table('dataset',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('schema', sa.JSON(), nullable=False, comment='Defines field names, types, and constraints'),
    sa.Column('procedure_id', sa.Integer(), nullable=True, comment='e.g., QC measurements for procedure X'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['procedure_id'], ['master_procedure.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dataset', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dataset_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_dataset_procedure_id'), ['procedure_id'], unique=False)

    op.create_table('inventory_record',
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False, comment='Physical location identifier'),
    sa.Column('lot_number', sa.String(length=100), nullable=True),
    sa.Column('last_counted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['part_id'], ['part.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_record_location'), ['location'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_record_lot_number'), ['lot_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_record_part_id'), ['part_id'], unique=False)

    op.create_table('kit',
    sa.Column('procedure_id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('quantity_required', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['part_id'], ['part.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['procedure_id'], ['master_procedure.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kit_part_id'), ['part_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_kit_procedure_id'), ['procedure_id'], unique=False)

    op.create_table('procedure_step',
    sa.Column('procedure_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False, comment='Position in sequence'),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True, comment='Markdown'),
    sa.Column('required_data_schema', sa.JSON(), nullable=True, comment='Defines what data to capture'),
    sa.Column('is_contingency', sa.Boolean(), nullable=False, comment='Only shown if NC logged'),
    sa.Column('estimated_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['procedure_id'], ['master_procedure.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('procedure_step', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_procedure_step_procedure_id'), ['procedure_id'], unique=False)

    op.create_table('procedure_version',
    sa.Column('procedure_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False, comment='1, 2, 3... per procedure'),
    sa.Column('content', sa.JSON(), nullable=False, comment='Full snapshot of steps at publish time'),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['procedure_id'], ['master_procedure.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('procedure_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_procedure_version_procedure_id'), ['procedure_id'], unique=False)

    op.create_table('purchase_line',
    sa.Column('purchase_id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('qty_ordered', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('qty_received', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['part_id'], ['part.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchase.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_line', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_line_part_id'), ['part_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_line_purchase_id'), ['purchase_id'], unique=False)

    op.create_table('procedure_instance',
    sa.Column('procedure_id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False, comment='Locked at start'),
    sa.Column('work_order_number', sa.String(length=100), nullable=True, comment='For grouping related instances'),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_by_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['procedure_id'], ['master_procedure.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['started_by_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['version_id'], ['procedure_version.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('procedure_instance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_procedure_instance_procedure_id'), ['procedure_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_procedure_instance_version_id'), ['version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_procedure_instance_work_order_number'), ['work_order_number'], unique=False)

    op.create_table('step_execution',
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False, comment='References step order from version snapshot'),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('data_captured', sa.JSON(), nullable=True, comment="Values matching step's required_data_schema"),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_by_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['completed_by_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['instance_id'], ['procedure_instance.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('step_execution', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_step_execution_instance_id'), ['instance_id'], unique=False)

    op.create_table('attachment',
    sa.Column('original_filename', sa.String(length=255), nullable=False, comment='Original uploaded filename'),
    sa.Column('stored_filename', sa.String(length=255), nullable=False, comment='UUID-based filename on disk'),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('procedure_instance_id', sa.Integer(), nullable=True),
    sa.Column('step_execution_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['procedure_instance_id'], ['procedure_instance.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['step_execution_id'], ['step_execution.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_filename')
    )
    with op.batch_alter_table('attachment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attachment_procedure_instance_id'), ['procedure_instance_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attachment_step_execution_id'), ['step_execution_id'], unique=False)

    op.create_table('data_point',
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('values', sa.JSON(), nullable=False, comment='Data matching dataset schema'),
    sa.Column('step_execution_id', sa.Integer(), nullable=True, comment='If captured during step execution'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['step_execution_id'], ['step_execution.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('data_point', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_point_dataset_id'), ['dataset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_point_recorded_at'), ['recorded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_point_step_execution_id'), ['step_execution_id'], unique=False)

    op.create_table('issue',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('issue_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=True),
    sa.Column('procedure_id', sa.Integer(), nullable=True),
    sa.Column('procedure_instance_id', sa.Integer(), nullable=True),
    sa.Column('step_execution_id', sa.Integer(), nullable=True, comment='For NC issues created during step execution'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['part_id'], ['part.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['procedure_id'], ['master_procedure.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['procedure_instance_id'], ['procedure_instance.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['step_execution_id'], ['step_execution.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('issue', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_issue_part_id'), ['part_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_issue_procedure_id'), ['procedure_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_issue_procedure_instance_id'), ['procedure_instance_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_issue_step_execution_id'), ['step_execution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_issue_title'), ['title'], unique=False)

    op.create_table('risk',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('probability', sa.Integer(), nullable=False, comment='1-5 scale'),
    sa.Column('impact', sa.Integer(), nullable=False, comment='1-5 scale'),
    sa.Column('mitigation_plan', sa.Text(), nullable=True),
    sa.Column('linked_issue_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['linked_issue_id'], ['issue.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('risk', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_linked_issue_id'), ['linked_issue_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_title'), ['title'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('risk', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_title'))
        batch_op.drop_index(batch_op.f('ix_risk_linked_issue_id'))

    op.drop_table('risk')
    with op.batch_alter_table('issue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_issue_title'))
        batch_op.drop_index(batch_op.f('ix_issue_step_execution_id'))
        batch_op.drop_index(batch_op.f('ix_issue_procedure_instance_id'))
        batch_op.drop_index(batch_op.f('ix_issue_procedure_id'))
        batch_op.drop_index(batch_op.f('ix_issue_part_id'))

    op.drop_table('issue')
    with op.batch_alter_table('data_point', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_point_step_execution_id'))
        batch_op.drop_index(batch_op.f('ix_data_point_recorded_at'))
        batch_op.drop_index(batch_op.f('ix_data_point_dataset_id'))

    op.drop_table('data_point')
    with op.batch_alter_table('attachment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attachment_step_execution_id'))
        batch_op.drop_index(batch_op.f('ix_attachment_procedure_instance_id'))

    op.drop_table('attachment')
    with op.batch_alter_table('step_execution', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_step_execution_instance_id'))

    op.drop_table('step_execution')
    with op.batch_alter_table('procedure_instance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_procedure_instance_work_order_number'))
        batch_op.drop_index(batch_op.f('ix_procedure_instance_version_id'))
        batch_op.drop_index(batch_op.f('ix_procedure_instance_procedure_id'))

    op.drop_table('procedure_instance')
    with op.batch_alter_table('purchase_line', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_line_purchase_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_line_part_id'))

    op.drop_table('purchase_line')
    with op.batch_alter_table('procedure_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_procedure_version_procedure_id'))

    op.drop_table('procedure_version')
    with op.batch_alter_table('procedure_step', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_procedure_step_procedure_id'))

    op.drop_table('procedure_step')
    with op.batch_alter_table('kit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kit_procedure_id'))
        batch_op.drop_index(batch_op.f('ix_kit_part_id'))

    op.drop_table('kit')
    with op.batch_alter_table('inventory_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_record_part_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_record_lot_number'))
        batch_op.drop_index(batch_op.f('ix_inventory_record_location'))

    op.drop_table('inventory_record')
    with op.batch_alter_table('dataset', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dataset_procedure_id'))
        batch_op.drop_index(batch_op.f('ix_dataset_name'))

    op.drop_table('dataset')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_timestamp'))
        batch_op.drop_index(batch_op.f('ix_audit_log_table_name'))
        batch_op.drop_index(batch_op.f('ix_audit_log_record_id'))

    op.drop_table('audit_log')
    op.drop_table('user')
    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_supplier'))

    op.drop_table('purchase')
    with op.batch_alter_table('part', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_part_name'))
        batch_op.drop_index(batch_op.f('ix_part_external_pn'))
        batch_op.drop_index(batch_op.f('ix_part_category'))

    op.drop_table('part')
    with op.batch_alter_table('master_procedure', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_master_procedure_name'))

    op.drop_table('master_procedure')
    # ### end Alembic commands ###
