"""add_is_admin_to_user

Revision ID: ec12ee94b679
Revises: 69d87e56ce80
Create Date: 2026-02-18 21:52:14.942217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec12ee94b679'
down_revision: Union[str, None] = '69d87e56ce80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False, server_default=sa.text('0')))

    # Set the first active user as admin
    op.execute("UPDATE user SET is_admin = 1 WHERE id = (SELECT MIN(id) FROM user WHERE is_active = 1)")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
