"""add procedure output and inventory production

Revision ID: ed7deb9d898c
Revises: 90e94a084627
Create Date: 2025-12-29 03:54:19.478382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed7deb9d898c'
down_revision: Union[str, None] = '90e94a084627'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('procedure_output',
    sa.Column('procedure_id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False, comment='The part/assembly that this procedure produces'),
    sa.Column('quantity_produced', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['part_id'], ['part.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['procedure_id'], ['master_procedure.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('procedure_output', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_procedure_output_part_id'), ['part_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_procedure_output_procedure_id'), ['procedure_id'], unique=False)

    op.create_table('inventory_production',
    sa.Column('inventory_record_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=15, scale=4), nullable=False, comment='Positive value = produced'),
    sa.Column('procedure_instance_id', sa.Integer(), nullable=True),
    sa.Column('serial_number', sa.String(length=100), nullable=True, comment='Serial for trackable assemblies'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('produced_by_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['inventory_record_id'], ['inventory_record.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['procedure_instance_id'], ['procedure_instance.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['produced_by_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_production', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_production_inventory_record_id'), ['inventory_record_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_production_procedure_instance_id'), ['procedure_instance_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_production_serial_number'), ['serial_number'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_production', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_production_serial_number'))
        batch_op.drop_index(batch_op.f('ix_inventory_production_procedure_instance_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_production_inventory_record_id'))

    op.drop_table('inventory_production')
    with op.batch_alter_table('procedure_output', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_procedure_output_procedure_id'))
        batch_op.drop_index(batch_op.f('ix_procedure_output_part_id'))

    op.drop_table('procedure_output')
    # ### end Alembic commands ###
